var
labelTituloPrincipal = `EJERCICIO ANDRÉS GUASTAVINO`,
labelTituloAmigosSinInvitar = `Amigos Sin Invitar`,
labelTituloAmigosInvitados = `Amigos Invitados`,
labelTituloFichaPersonal = `Ficha Personal`,
labelFichaPersonalNombre = `Nombre: `,
labelFichaPersonalDomicilio = `Domicilio: `,
labelAmigo1SinInvitarNombre= `Nombre: `,
labelAmigo1SinInvitarEdad = `Edad: `,
labelAmigo2SinInvitarNombre= `Nombre: `,
labelAmigo2SinInvitarEdad = `Edad: `,
labelAmigo3SinInvitarNombre= `Nombre: `,
labelAmigo3SinInvitarEdad = `Edad: `,
labelAmigo4SinInvitarNombre= `Nombre: `,
labelAmigo4SinInvitarEdad = `Edad: `,
labelAmigo1InvitadoNombre= `Nombre: `,
labelAmigo1InvitadoEdad = `Edad: `,
labelAmigo2InvitadoNombre= `Nombre: `,
labelAmigo2InvitadoEdad = `Edad: `,
labelAmigo3InvitadoNombre= `Nombre: `,
labelAmigo3InvitadoEdad = `Edad: `,
labelAmigo4InvitadoNombre= `Nombre: `,
labelAmigo4InvitadoEdad = `Edad: `,
nombreFichaPersonal = `Andrés Guastavino`,
domicilioFichaPersonal = `Via Astiere 15`,
NombreAmigo1SinInvitar = `Gonzalo Perez`,
NombreAmigo2SinInvitar = `Ricardo Ramirez`,
NombreAmigo3SinInvitar = `Lautaro Solis`,
NombreAmigo4SinInvitar = `Pedro Romualdo`,
EdadAmigo1SinInvitar = 20,
EdadAmigo2SinInvitar = 20,
EdadAmigo3SinInvitar = 20,
EdadAmigo4SinInvitar = 20,
NombreAmigo1Invitado,
NombreAmigo2Invitado ,
NombreAmigo3Invitado ,
NombreAmigo4Invitado ,
EdadAmigo1Invitado,
EdadAmigo2Invitado,
EdadAmigo3Invitado,
EdadAmigo4Invitado,
btnInvitarAmigo1,
btnInvitarAmigo2,
btnInvitarAmigo3,
btnInvitarAmigo4,
btnDesivitarAmigo1,
btnDesinvitarAmigo2,
btnDesinvitarAmigo3,
btnDesinvitarAmigo4;



